// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApSK7GXLQRdaSt2YZHDP0GfKiVmz1Gjy4',
    appId: '1:774223061643:web:da2287c6f59c543fb86a8e',
    messagingSenderId: '774223061643',
    projectId: 'bookswapapp-b6457',
    authDomain: 'bookswapapp-b6457.firebaseapp.com',
    storageBucket: 'bookswapapp-b6457.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD-oU1u2etjRG4kjMXEMbCkywy5g-D9oA',
    appId: '1:774223061643:android:91305039834e84b2b86a8e',
    messagingSenderId: '774223061643',
    projectId: 'bookswapapp-b6457',
    storageBucket: 'bookswapapp-b6457.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx7ciHjPhBIf5WcOb28ebOJKNqOnoWodM',
    appId: '1:774223061643:ios:94104f681b8d4c47b86a8e',
    messagingSenderId: '774223061643',
    projectId: 'bookswapapp-b6457',
    storageBucket: 'bookswapapp-b6457.firebasestorage.app',
    iosBundleId: 'com.glorypaul.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx7ciHjPhBIf5WcOb28ebOJKNqOnoWodM',
    appId: '1:774223061643:ios:722e9cbf1b64978eb86a8e',
    messagingSenderId: '774223061643',
    projectId: 'bookswapapp-b6457',
    storageBucket: 'bookswapapp-b6457.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApSK7GXLQRdaSt2YZHDP0GfKiVmz1Gjy4',
    appId: '1:774223061643:web:52193a875023fcd5b86a8e',
    messagingSenderId: '774223061643',
    projectId: 'bookswapapp-b6457',
    authDomain: 'bookswapapp-b6457.firebaseapp.com',
    storageBucket: 'bookswapapp-b6457.firebasestorage.app',
  );
}
